### ISSUE TITLE
Améliorer l'intégration des trajets en Ferry

### ISSUE THREAD

**Issue by AnitaChains** [Travel-my-way/api#8]
On veut pouvoir bon voyager en Ferry.
On a déjà des données qui peuvent renvoyer des trajets.
On connaît les ports ; on doit ensuite constituer un trajet entre l'adresse choisie et le port.
On peut faire faire ce trajet en voiture, mais l'idéal serait de faire une nouvelle requête pour trouver des résultats complets sur ce trajet.

**Comment by baptistesola2** [comment]
La PR https://github.com/Travel-my-way/api/pull/10 devrait régler ça
