### ISSUE TITLE
S'assurer qu'on a toujours un eC02 pour l'avion

### ISSUE THREAD

**Issue by AnitaChains** [Travel-my-way/api#9]
A priori, Kombo nous donne des résultats pour ces trajets. Cependant, c'est un élément clef pour la comparaison avec les trajets moins impactants, donc il faut s'assurer qu'on a toujours un résultat, même si Kombo ne nous en fournit pas.

On suggère les solutions suivantes : 
- Calculer l'eCO2 sur la distance à vol d'oiseau * eCO2 moyen de l'avion
- Trouver une autre API qui puisse nous fournir des résultats

**Comment by baptistesola2** [comment]
Aller là ! #12
